version: '3'
services:
  web:
    container_name: ducksmanager
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8000:80"
    volumes:
     - dm_sessions:/tmp
     - .:/var/www/html
     - ./php.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: always
    networks:
      - dm-server_front-network
networks:
  dm-server_front-network:
    external: true

volumes:
    dm_sessions:
