version: '2'
services:
  web:
    container_name: ducksmanager
    build:
      context: .
      args:
        COMMIT_HASH: ${COMMIT_HASH}
    volumes:
    - dm_sessions:/tmp
    environment:
      ENV: 'production'
    networks:
      dm-server_front-network:
        aliases:
          - ducksmanager
      workspace_global-front-network:
        aliases:
          - ducksmanager

networks:
  workspace_global-front-network:
    external: true
  dm-server_front-network:
    external: true

volumes:
  dm_sessions:
